name: Deploy to Google Cloud

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v2'
      with:
        name: 'corso-function'
        runtime: 'nodejs20'
        entry_point: 'helloWorld'
        memory_mb: 128
        region: 'us-central1'
        timeout: 10
  